### ISSUE TITLE
证书问题

### ISSUE THREAD

**Issue by lushi78778** [firemakergk/aquar-home#10]
https证书需要更换，docker下如何修改？
可否只是用http，我想把剩下的交给nginx做

**Comment by firemakergk** [comment]
在aquardata目录下创建一个cert/目录，里面放aquarhome.key和aquarhome.cert就可以覆盖默认的证书了，因为aquarhome集成了webrtc实时视频功能，而webrtc强制要求使用https，所以暂时不能用http访问，不过nginx应该可以把http转成https吧
