### ISSUE TITLE
请求添加casaos支持

### ISSUE THREAD

**Issue by QueenLoli** [firemakergk/aquar-home#16]
请求添加对[casaos](https://github.com/IceWhaleTech/CasaOS)的支持。

**Comment by firemakergk** [comment]
第一次知道这个系统，做的好棒，还是中国人开发的，但是这个系统并没有开放api，所以AquarHome暂时无法支持，另外他的功能与AquarHome有一定重合，如果需要导航功能，直接用casaos即可。
