### ISSUE TITLE
可以支持Unraid吗？

### ISSUE THREAD

**Issue by bitswall** [firemakergk/aquar-home#18]
我在选择nas系统之前，看了很久的nas os，最终选择的unraid，而不是truenas，主要是因为unraid可以支持不同硬盘大小的硬盘混插，而且不用想zfs那样吃内存。可以对不访问的硬盘实施休眠，非常适合个人用户。群主可以让组建支持unraid吗？

**Comment by firemakergk** [comment]
unraid作为闭源系统没有找到完整的api文档，所以无法集成。而且unraid本身的功能很丰富，很难用一个小组件概括起来。
