### ISSUE TITLE
要不要压缩下体积...

### ISSUE THREAD

**Issue by lalasou** [firemakergk/aquar-home#3]
好大 
好大

**Comment by firemakergk** [comment]
这个得承认是挺大的，原因主要是系统的功能比较多，有像处理的库，有流媒体的库，这些都是C ++的，需要在镜像上装很多东西，未来可能会使用alpine基础镜像去打包，那样能让镜像小一点，但也只是一点。暂时我也没想到其他好办法。

**Comment by lalasou** [comment]
说实话  就单纯导航页来说还是很不错的 
能不能 出个精简版  
只简单的导航页

**Comment by firemakergk** [comment]
这倒是可以，但在技术实践上还需要研究一下构建方案，怎么用一套js代码构建两个版本。感谢提建议。

**Comment by ShuBo6** [comment]
> 这个得承认是挺大的，原因主要是系统的功能比较多，有像处理的库，有流媒体的库，这些都是C ++的，需要在镜像上装很多东西，未来可能会使用alpine基础镜像去打包，那样能让镜像小一点，但也只是一点。暂时我也没想到其他好办法。

还没有试用，看了下镜像1.42G。然后回来简单看了下docker file，感觉还可以优化。dockerfile可以搞成多阶段构建，编译步骤放在编译阶段就好了，最终将编译好的可执行程序拷贝到最终阶段的运行容器里，这可以大大减小编译构建层造成的体积臃肿，以及冗余的源代码和编译依赖程序造成的空间占用。例如前端程序vue打包后是不是可以只保留dist？后端程序，看起来用了一个叫pm2-runtime的东西，这个玩意能不能也像前端程序一样打包后只丢一个可执行文件进来呢？

**Comment by firemakergk** [comment]
最近用多阶重新优化了一下，比之前的体积小了一半以上，目前基础镜像还是在slim上，alpine估计难度就比较大了，这个系统对第三方的依赖很多，可能编译一通下来也不比slim小了。这个issue先关了，感谢建议。
