### ISSUE TITLE
如何链接PVE

### ISSUE THREAD

**Issue by musaart** [firemakergk/aquar-home#6]
我看到教程里没有pve的参数获取，不晓得如何填写。楼主有空更新下教程么，另外是否能增加对esxi的支持，也有好多人用这个的

**Comment by firemakergk** [comment]
好的pve的文档我会补上，因为pve修改过一次认证过程，所以旧版的没发上来。
另外esxi没有api可用，我找了很久资料，他虽然有个api文档，但是调不通。

**Comment by longcat99** [comment]
试了很久不行

**Comment by longcat99** [comment]
![image](https://user-images.githubusercontent.com/33887488/197343260-7583fdad-5cfc-4fbd-b30e-44c93c811ab9.png)
链接就是登录的链接随便啦
server填写:https://your.server:8006
![image](https://user-images.githubusercontent.com/33887488/197343525-a50cceee-678a-4b81-ba7c-202ece1eb7d4.png)

**Comment by firemakergk** [comment]
sorry，最近工作过于繁忙，一直没空更项目，下面这个兄弟写的很棒！就是这样的。

**Comment by solider245** [comment]
> ![image](https://user-images.githubusercontent.com/33887488/197343260-7583fdad-5cfc-4fbd-b30e-44c93c811ab9.png) 链接就是登录的链接随便啦 server填写:https://your.server:8006 ![image](https://user-images.githubusercontent.com/33887488/197343525-a50cceee-678a-4b81-ba7c-202ece1eb7d4.png)

我这边无法识别网卡，连网络都没有，插了下，似乎是CPU的问题，但是我是E3的CPU，奇怪了

**Comment by zhy201810576** [comment]
各位，在PVE添加令牌是记得**不要勾选“特权分离”**，不然API会因为没有权限而无法获取数据。

**Comment by firemakergk** [comment]
https://github.com/firemakergk/aquar-home-helper/blob/master/app/Pve.md
我在帮助文档上更新了pve的章节，感谢反馈问题的朋友和自行解答的朋友！
